<?php $idUser = $this->identity()->getId();?>
<div class="page-header">
	<h1><i class="fa fa-fw fa-link"></i>&nbsp;<?php echo $this->escapehtml('Associer une IP existante à une machine')?></h1>
</div>
<p>
	<?php echo $this->escapehtml(sprintf($this->translate('Vous êtes sur le point d\'associer la machine « %s » à une IP existante. Sélectionnez l\'adresse IP de votre choix. Préférez les IPs que vous avez vous-même référencées.'),$this->uneMachine->getLibelle()));?>
<?php
	$flash = $this->flashmessenger();
	echo $flash->render('error',   array('alert', 'alert-dismissable', 'alert-danger'));
	echo $flash->render('warning', array('alert', 'alert-dismissable', 'alert-warning'));
	echo $flash->render('info',    array('alert', 'alert-dismissable', 'alert-info'));
	echo $flash->render('default', array('alert', 'alert-dismissable', 'alert-warning'));
	echo $flash->render('success', array('alert', 'alert-dismissable', 'alert-success'));
?>
<?php if (is_array($this->ips) && count($this->ips)):?>
<table class="table table-condensed table-hover table-striped">
	<thead>
		<tr>
			<th id="number">#</th>
			<th id="ips_adresse"><?php echo $this->escapehtml($this->translate('Adresse IP'));?></th>
			<th id="ips_libelle"><?php echo $this->escapehtml($this->translate('Informations'));?></th>
			<th id="ips_libelle"><?php echo $this->escapehtml($this->translate('Référencée par'));?></th>
			<th id="action"></th>
		</tr>
	</thead>
	<tbody>
		<?php foreach ($this->ips as $key => $ip):?>
		<tr class="<?php echo ($ip->getCreateurId() == $idUser)?'success':'warning';?>">
			<td headers="number"><?php echo $this->escapehtml($key + 1);?></td>
			<td headers="ips_adresse"><?php echo $this->ip($ip->getIp());?></td>
			<td headers="ips_libelle"><?php echo $this->escapehtml($ip->getLibelle());?></td>
			<td headers="ips_createur"><?php echo $this->escapehtml($ip->getCreateurUsername());?></td>
			<td headers="action">
				<div class="btn-group">
				    <a class="btn btn-primary btn-xs tooltip-link"
						href="<?php echo $this->url('machine',array('action' => 'associerIp', 'reseau' => $this->unReseau->getId(), 'machine' => $this->uneMachine->getId(), 'ip' => $ip->getId()));?>"
						title="<?php echo $this->escapehtmlattr(sprintf($this->translate('Associer l\'IP %s à la machine %s'),$this->ip($ip->getIp()),$this->uneMachine->getLibelle()));?>">
						<i class="fa fa-link"></i>&nbsp;Associer
					</a>
				</div>
			</td>
		</tr>
		<?php endforeach;?>
	</tbody>
	<tfoot>
		<tr>
			<th headers="number">#</th>
			<th headers="ips_adresse"><?php echo $this->escapehtml($this->translate('Adresse IP'));?></th>
			<th headers="ips_libelle"><?php echo $this->escapehtml($this->translate('Informations'));?></th>
			<th headers="ips_libelle"><?php echo $this->escapehtml($this->translate('Référencée par'));?></th>
			<th headers="action"></th>
		</tr>
	</tfoot>
</table>
<hr/>
<?php $message = $this->translate('Si aucune de ces IPs n\'est satisfaisante, vous pouvez en créer une nouvelle et l\'associer automatiquement à cette machine en cliquant sur le bouton suivant.');?>
<?php else:?>
<?php $message = $this->translate('Le réseau %s ne dispose pas d\'adresse IP libre. Les IPs référencées de ce réseau sont déjà toutes associées à une machine. Vous pouvez référencer une nouvelle IP dans ce réseau et l\'associer à la machine courante en cliquant sur le bouton suivant');?>
<?php endif;?>
<div class="row">
	<div class="col-sm-9">
		<p class="alert alert-info text-center">
			<?php echo $this->escapehtml($message);?>
		</p>
	</div>
	<div class="col-sm-3">
		<span class="">
			<a href="<?php echo $this->url('machine',array('action'=>'creerIp','machine'=>$this->uneMachine->getId(),'reseau'=>$this->unReseau->getId()));?>"
			  title="<?php echo $this->escapehtmlattr($this->translate('Créer une nouvelle IP et l\'associer automatiquement à cette machine'));?>"
			  class="btn btn-primary tooltip-link">
			  <i class="fa fa-fw fa-plus"></i>&nbsp;
			  Créer une IP
			</a>
		</span>
	</div>
</div>
