<div class="page-header">
	<h1><?php echo sprintf($this->translate('Détail de la machine %s'),'<strong>'.$this->escapehtml($this->uneMachine->getLibelle()).'</strong>');?></h1>
</div>
<?php
	$flash = $this->flashmessenger();
	echo $flash->render('error',   array('alert', 'alert-dismissable', 'alert-danger'));
	echo $flash->render('warning', array('alert', 'alert-dismissable', 'alert-warning'));
	echo $flash->render('info',    array('alert', 'alert-dismissable', 'alert-info'));
	echo $flash->render('default', array('alert', 'alert-dismissable', 'alert-warning'));
	echo $flash->render('success', array('alert', 'alert-dismissable', 'alert-success'));
?>
<div class="row text-justify">
	<div class="col-sm-6">
		<div class="panel panel-primary">
			<div class="panel-heading">
				<h2 class="panel-title">
					<?php echo $this->translate('Généralités');?>
				</h2>
			</div>
			<div class="panel-body">
				<dl class="dl-horizontal">
					<dt><?php echo $this->translate('Type');?></dt>
					<dd><?php echo $this->escapehtml($this->uneMachine->getType());?></dd>
				</dl>
				<dl class="dl-horizontal">
					<dt><?php echo $this->translate('Libellé');?></dt>
					<dd><?php echo $this->escapehtml($this->uneMachine->getLibelle());?></dd>
				</dl>
				<dl class="dl-horizontal">
					<dt><?php echo $this->translate('Description');?></dt>
					<dd><?php echo $this->escapehtml($this->uneMachine->getDescription());?></dd>
				</dl>
				<dl class="dl-horizontal">
					<dt><?php echo $this->translate('Nb d\'interfaces');?></dt>
					<dd><?php echo $this->escapehtml($this->uneMachine->getInterface());?></dd>
				</dl>
			</div>
			<div class="panel-footer text-right">
				<small><em><?php echo $this->escapehtml(sprintf($this->translate('Machine référencée par %s'),$this->uneMachine->getUsername()));?></em></small>
			</div>
		</div>
	</div>
	<div class="col-sm-6">
		<div class="panel panel-default">
			<div class="panel-heading">
				<h2 class="panel-title">
					<?php echo $this->translate('Actions');?>
				</h2>
			</div>
			<div class="panel-body text-center">
				<div class="btn-group">
					<a class="btn btn-default"
					    href=""
					    title="<?php echo$this->escapehtmlattr($this->translate(''));?>">
						<i class="fa fa-plus"></i>
						<?php echo $this->escapehtml($this->translate(''));?>
					</a>
					<a class="btn btn-default"
					    href="<?php echo $this->url('machine',array('action' => 'reserverIP', 'reseau' => $this->uneMachine->getId()));?>"
					   title="<?php echo $this->escapehtmlattr($this->translate(''));?>">
						<i class="fa fa-plus"></i>
						<?php echo$this->escapehtml($this->translate(''));?>
					</a>
				</div>
			</div>
		</div>
	</div>
</div>
<?php if (is_array($this->ips) && count($this->ips)):?>
<table class="table table-condensed table-hover table-striped">
	<thead>
		<tr>
			<th id="number">#</th>
			<th id="ips_adresse"><?php echo $this->escapehtml($this->translate('Adresse IP'));?></th>
			<th id="ips_libelle"><?php echo $this->escapehtml($this->translate('Informations'));?></th>
			<th id="ips_libelle"><?php echo $this->escapehtml($this->translate('Référencé par'));?></th>
			<th id="ips_reseau"><?php echo $this->escapehtml($this->translate('Réseau'));?></th>
			<th id="action"></th>
		</tr>
	</thead>
	<tbody>
		<?php foreach ($this->ips as $key => $ip):?>
		<tr>
			<td headers="number"><?php echo $this->escapehtml($key + 1);?></td>
			<td headers="ips_adresse"><?php echo $this->ip($ip->getIp());?></td>
			<td headers="ips_libelle"><?php echo $this->escapehtml($ip->getLibelle());?></td>
			<td headers="ips_createur"><?php echo $this->escapehtml($ip->getCreateurUsername());?></td>
			<td headers="ips_reseau">
				<a href="<?php echo $this->url('reseau',array('action'=>'consulter','reseau'=>$ip->getReseauId()));?>"
				  title="<?php echo $this->escapehtmlattr(sprintf($this->translate('Accéder au réseau %s'),$ip->getReseauLibelle()));?>">
				<?php echo $this->escapehtml($ip->getReseauLibelle());?>
				</a>
				&bull;
				<?php echo $this->escapehtml($ip->getReseauCIDR());?>
			</td>
			<td headers="action">
				<div class="btn-group">
				    <a class="btn btn-warning btn-xs tooltip-link"
						href="<?php echo $this->url('reseau',array('action' => 'dissocierIp', 'reseau' => $ip->getReseauId(), 'ip' => $ip->getId()));?>"
						title="<?php echo $this->escapehtmlattr($this->translate('Dissocier une IP d\'une machine'));?>">
						<i class="fa fa-unlink"></i>
					</a>
					<a class="btn btn-danger btn-xs tooltip-link"
						href="<?php echo $this->url('reseau',array('action' => 'supprimerIp', 'reseau' => $ip->getReseauId(), 'ip' => $ip->getId()));?>"
						title="<?php echo $this->escapehtmlattr($this->translate('Supprimer cette adresse Ip'));?>">
						<i class="fa fa-trash-o"></i>
					</a>
				</div>
			</td>
		</tr>
		<?php endforeach;?>
	</tbody>
	<tfoot>
		<tr>
			<th headers="number">#</th>
			<th headers="ips_adresse"><?php echo $this->escapehtml($this->translate('Adresse IP'));?></th>
			<th headers="ips_libelle"><?php echo $this->escapehtml($this->translate('Informations'));?></th>
			<th headers="ips_libelle"><?php echo $this->escapehtml($this->translate('Référencé par'));?></th>
			<th headers="ips_machine"><?php echo $this->escapehtml($this->translate('Réseau'));?></th>
			<th headers="action"></th>
		</tr>
	</tfoot>

</table>
<?php endif;?>
