<?php $cpt = 0;?>
<div class="page-header">
	<div class="btn-grp pull-right">
		<a class="btn btn-primary" href="<?php echo $this->url('machine',array('action' => 'creer'));?>" title="<?php echo $this->escapehtmlattr($this->translate('Référencer une nouvelle machine'))?>">
			<i class="fa fa-desktop fa-fw"></i>&nbsp;<?php echo $this->escapehtml($this->translate('Référencer une nouvelle machine'));?>
		</a>
	</div>
	<h1><?php echo $this->escapehtml($this->translate('Listing des machines référencées'))?></h1>
</div>
<?php
	$flash = $this->flashmessenger();
	echo $flash->render('error',   array('alert', 'alert-dismissable', 'alert-danger'));
	echo $flash->render('warning', array('alert', 'alert-dismissable', 'alert-warning'));
	echo $flash->render('info',    array('alert', 'alert-dismissable', 'alert-info'));
	echo $flash->render('default', array('alert', 'alert-dismissable', 'alert-warning'));
	echo $flash->render('success', array('alert', 'alert-dismissable', 'alert-success'));
?>
<div class="row text-justify">
<?php if (empty($this->machines)):?>
	<div class="col-sm-offset-3 col-sm-6">
		<div class="panel panel-primary">
			<div class="panel-heading">
				<h2 class="panel-title">
					<i class="fa fa-info-circle"></i>
					<?php echo $this->escapehtml($this->translate('Aucune machine'))?>
				</h2>
			</div>
			<div class="panel-body">
				<ul class="fa-ul">
					<li>
						<?php echo $this->escapehtml($this->translate("Aucune machine n'a encore été référencée dans l'application !"))?>
					</li>
				</ul>
			</div>
			<div class="panel-footer text-center">
				<a
					class="btn btn-primary"
					href="<?php echo $this->url('machine',array('action' => 'creer'));?>"
					title="<?php echo $this->escapehtmlattr($this->translate('Référencer une nouvelle machine'))?>">
					<i class="fa fa-desktop"></i>
					<?php echo $this->escapehtml($this->translate('Référencer une nouvelle machine'))?>
				</a>
			</div>
		</div>
	</div>
</div>
<?php else:?>
<table class="table table-hover table-striped table-bordered">
	<thead>
		<tr>
			<th id="number">#</th>
			<th id="machineLibelle">Machine</th>
			<th id="machineType">Type</th>
			<th id="machineInterface">Interfaces</th>
			<th id="machineCreateur">Référencée par</th>
			<th id="machineIp">IPs</th>
			<th id="machineReseau">Réseaux</th>
		</tr>
	</thead>
	<tbody>
		<?php foreach ($this->machines as $machine):?>
		<?php //@var Reseau\Entity\Table\Machine $machine ?>
		<?php $cpt++;?>
		<tr>
			<td headers="number"><?php echo $cpt;?></td>
			<td headers="machineLibelle"><?php echo $this->escapehtml($machine->getLibelle());?></td>
			<td headers="machineType"><?php echo $this->escapehtml($machine->getType());?></td>
			<td headers="machineInterface"><?php echo $this->escapehtml($machine->getInterface());?></td>
			<td headers="machineCreateur"><?php echo $this->escapehtml($machine->getCreateur()->getUsername());?></td>
			<td headers="machineIp"><?php echo $this->escapehtml($machine->getIpCount());?></td>
			<td headers="machineReseau"><?php echo $this->escapehtml($machine->getIpCount());?></td>
		</tr>
		<?php endforeach;?>
	</tbody>
	<tfoot>
		<tr>
			<th headers="number">#</th>
			<th headers="machineLibelle">Machine</th>
			<th headers="machineType">Type</th>
			<th headers="machineInterface">Interfaces</th>
			<th headers="machineCreateur">Référencée par</th>
			<th headers="machineIp">IPs</th>
			<th headers="machineReseau">Réseaux</th>
		</tr>
	</tfoot>
</table>
<div class="btn-grp pull-right">
	<a class="btn btn-primary" href="<?php echo $this->url('machine',array('action' => 'creer'));?>" title="<?php echo $this->escapehtmlattr($this->translate('Référencer une nouvelle machine'))?>">
		<i class="fa fa-desktop fa-fw"></i>&nbsp;<?php echo $this->escapehtml($this->translate('Référencer une nouvelle machine'));?>
	</a>
</div>
<?php endif;?>