<?php if (count($this->pages)):?>
	<ol class="breadcrumb">
		<li><i class="fa fa-road"></i>&nbsp;<a href="<?php echo $this->url('home')?>" title="<?php echo $this->translate('Home');?>">GMAO</a></li>
		<?php foreach ($this->pages as $page): ?>
		<?php /* @var $page Zend\Navigation\Page\Mvc */?> 
		<li><a href="<?php echo $page->getHref() ?>" <?php echo empty($page->getTitle())?'':'title="'.$this->translate($page->getTitle()).'"';?>><?php echo $this->translate($page->getLabel())?></a></li>
		<?php endforeach;?>
	</ol>
<?php endif;?>