<ul class="nav navbar-nav">
    <?php $count = 0 ?>
    <?php foreach ($this->container as $page): ?>
        <?php /* @var $page Zend\Navigation\Page\Mvc */ ?>
        <?php // when using partials we need to manually check for ACL conditions ?>
        <?php if( ! $page->isVisible() || !$this->navigation()->accept($page)) continue; ?>
        <?php $hasChildren = $page->hasPages() ?>
        <?php if( ! $hasChildren): ?>
        	<?php
        		$class="";
        		$class.=$page->isActive(true)?' active ':'';
        		$class.=$page->get('class')?$page->get('class'):'';
        	?>
        <li <?php if($class) echo 'class="'.$this->escapehtmlattr($class).'"';?>>
            <a class="nav-header" href="<?php echo $page->getHref() ?>" <?php if ($page->getTitle()) echo 'title="'.$this->escapehtmlattr($page->getTitle()).'"'; ?>>
	           	<?php if ($page->get('icon')):?>
	            <i class="fa fa-fw fa-<?php echo $page->get('icon');?>"></i>
	            <?php endif;?>
	            <?php echo $this->translate($page->getLabel()) ?>
            </a>
        </li>
        <?php else: ?>
        <li class="dropdown <?php if ($page->isActive(true)) echo ' active';?>">
            <a class="dropdown-toggle" data-toggle="dropdown" href="#">
	           	<?php if ($page->get('icon')):?>
	            <i class="fa fa-fw fa-<?php echo $page->get('icon');?>"></i>
	            <?php endif;?>
            <span><?php echo $this->translate($page->getLabel()) ?>&nbsp;<b class="caret"></b></span>
            </a>

            <ul class="dropdown-menu" id="page_<?php echo $count ?>">
            <?php foreach($page->getPages() as $child): ?>
                <?php // when using partials we need to manually check for ACL conditions ?>
                <?php if( ! $child->isVisible() || !$this->navigation()->accept($child)) continue; ?>
                <li>
                    <a href="<?php echo $child->getHref() ?>" <?php if ($child->getTitle()) echo 'title="'.$this->translate($child->getTitle()).'"'; ?>>
                    	<?php if ($child->get('icon')):?>
                        <i class="fa fa-fw fa-<?php echo $child->get('icon');?>"></i>
                        <?php endif;?>
                        <?php echo $this->translate($child->getLabel()) ?>
                    </a>
                </li>
            <?php endforeach ?>
            </ul>
         </li>
        <?php endif ?>
        <?php $count++ ?>
    <?php endforeach ?>
</ul>