<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Utilisateur\Module'                        => __DIR__ . '/Module.php',
    'Utilisateur\Controller\IndexController' 	=> __DIR__ . '/src/Utilisateur/Controller/IndexController.php',
    'Utilisateur\Controller\RegistrationController' 	=> __DIR__ . '/src/Utilisateur/Controller/RegistrationController.php',
	'UtilisateurTest\Framework\TestCase'        => __DIR__ . '/tests/Utilisateur/Framework/TestCase.php',
    'UtilisateurTest\SampleTest'                => __DIR__ . '/tests/Utilisateur/SampleTest.php',
);
