<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Reseau\Module'                        => __DIR__ . '/Module.php',
    'Reseau\Controller\IndexController' => __DIR__ . '/src/Reseau/Controller/IndexController.php',
    'ReseauTest\Framework\TestCase'        => __DIR__ . '/tests/Reseau/Framework/TestCase.php',
    'ReseauTest\SampleTest'                => __DIR__ . '/tests/Reseau/SampleTest.php',
);
