<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Machine\Module'                        => __DIR__ . '/Module.php',
    'Machine\Controller\IndexController' => __DIR__ . '/src/Machine/Controller/IndexController.php',
    'MachineTest\Framework\TestCase'        => __DIR__ . '/tests/Machine/Framework/TestCase.php',
    'MachineTest\SampleTest'                => __DIR__ . '/tests/Machine/SampleTest.php',
);
