<div class="page-header">
	<h1><?php echo sprintf($this->translate('Détail du réseau %s'),'<strong>'.$this->escapehtml($this->unReseau->getLibelle()).'</strong>');?></h1>
</div>
<?php
	$flash = $this->flashmessenger();
	echo $flash->render('error',   array('alert', 'alert-dismissable', 'alert-danger'));
	echo $flash->render('warning', array('alert', 'alert-dismissable', 'alert-warning'));
	echo $flash->render('info',    array('alert', 'alert-dismissable', 'alert-info'));
	echo $flash->render('default', array('alert', 'alert-dismissable', 'alert-warning'));
	echo $flash->render('success', array('alert', 'alert-dismissable', 'alert-success'));
?>
<div class="row text-justify">
	<div class="col-sm-6">
		<div class="panel panel-primary">
			<div class="panel-heading">
				<h2 class="panel-title">
					<?php echo $this->translate('Généralités');?>
				</h2>
			</div>
			<div class="panel-body">
				<dl class="dl-horizontal">
					<dt><?php echo $this->translate('Libellé');?></dt>
					<dd><?php echo $this->escapehtml($this->unReseau->getLibelle());?></dd>
				</dl>
				<dl class="dl-horizontal">
					<dt><?php echo $this->translate('Description');?></dt>
					<dd><?php echo $this->escapehtml($this->unReseau->getDescription());?></dd>
				</dl>
				<dl class="dl-horizontal">
					<dt><?php echo $this->translate('IP Réseau');?></dt>
					<dd>
						<abbr title="<?php echo $this->escapehtmlattr($this->unReseau->getIP().' / '.$this->unReseau->getMasque());?>">
							<?php echo $this->escapehtml($this->unReseau->getCIDR());?>
						</abbr>
					</dd>
				</dl>
				<dl class="dl-horizontal">
					<dt><?php echo $this->translate('Broadcast');?>&nbsp;:</dt>
		  			<dd><?php echo $this->escapehtml($this->unReseau->getBroadcast());?></dd>
				</dl>
				<dl class="dl-horizontal">
					<dt><?php echo $this->translate('Passerelle');?></dt>
					<dd><?php echo $this->escapehtml($this->unReseau->getPasserelle());?></dd>
				</dl>
			</div>
			<div class="panel-footer text-right">
				<small><em><?php echo $this->escapehtml(sprintf($this->translate('Réseau référencé par %s'),$this->unReseau->getCreateurUsername()));?></em></small>
			</div>
		</div>
	</div>
	<div class="col-sm-6">
		<div class="panel panel-default">
			<div class="panel-heading">
				<h2 class="panel-title">
					<?php echo $this->translate('Actions');?>
				</h2>
			</div>
			<div class="panel-body text-center">
				<div class="btn-group">
					<a class="btn btn-default tooltip-link"
					    href="<?php echo $this->url('reseau',array('action' => 'referencerIP', 'reseau' => $this->unReseau->getId()));?>"
					   title="<?php echo$this->escapehtmlattr($this->translate('Créer une machine et une IP qui seront automatiquement associées'));?>">
						<i class="fa fa-link"></i>
						<?php echo $this->escapehtml($this->translate('Référencer une IP'));?>
					</a>
					<a class="btn btn-default tooltip-link"
					    href="<?php echo $this->url('reseau',array('action' => 'reserverIP', 'reseau' => $this->unReseau->getId()));?>"
					   title="<?php echo $this->escapehtmlattr($this->translate('Réserver une adresse IP sans y associer de machine'));?>">
						<i class="fa fa-plus"></i>
						<?php echo$this->escapehtml($this->translate('Réserver une IP'));?>
					</a>
				</div>
			</div>
		</div>
		<div class="panel panel-default">
			<div class="panel-heading">
				<h2 class="panel-title">
					<?php echo $this->translate('Adresses IP utilisées');?>
				</h2>
			</div>
			<div class="panel-body">
				<div class="progress">
					<?php
						$pourcentage = $this->escapehtmlattr(sprintf('%.0f',$this->unReseau->getIpPourcentageOccupe()));
						if( $this->unReseau->getIpPourcentageOccupe() < 60){
							$couleurBar = 'progress-bar-success';
						}elseif($this->unReseau->getIpPourcentageOccupe()<80){
							$couleurBar = 'progress-bar-warning';
						}else {
							$couleurBar = 'progress-bar-danger';
						}
					?>

					<div class="progress-bar <?php echo $couleurBar;?> progress-bar-striped" role="progressbar" aria-valuenow="<?php echo $pourcentage;?>" aria-valuemin="0" aria-valuemax="100">
		    			<?php echo $pourcentage?>%
		  			</div>
				</div>
				<dl class="dl-horizontal">
					<dt><?php echo $this->translate('Occupations IP');?>&nbsp;:</dt>
					<dd><?php echo sprintf('%d / %d',$this->unReseau->getQuantiteIp(),$this->unReseau->getIpTheoriquementDisponible())?></dd>
				</dl>
				<p>
					<em>
						<?php echo $this->escapehtmlattr(sprintf($this->translate('%d adresse IP occupée sur %d adresses théoriquement disponibles','%d adresses IP occupées sur %d adresses théoriquement disponibles',$this->unReseau->getQuantiteIp()),$this->unReseau->getQuantiteIp(),$this->unReseau->getIpTheoriquementDisponible()));?>
					</em>
				</p>
			</div>
		</div>
	</div>
</div>
<?php if (is_array($this->ips) && count($this->ips)):?>
<table class="table table-condensed table-hover table-striped">
	<thead>
		<tr>
			<th id="number">#</th>
			<th id="ips_adresse"><?php echo $this->escapehtml($this->translate('Adresse IP'));?></th>
			<th id="ips_libelle"><?php echo $this->escapehtml($this->translate('Informations'));?></th>
			<th id="ips_libelle"><?php echo $this->escapehtml($this->translate('Référencé par'));?></th>
			<th id="ips_machine"><?php echo $this->escapehtml($this->translate('Machine'));?></th>
			<th id="action"></th>
		</tr>
	</thead>
	<tbody>
		<?php foreach ($this->ips as $key => $ip):?>
		<tr>
			<td headers="number"><?php echo $this->escapehtml($key + 1);?></td>
			<td headers="ips_adresse"><?php echo $this->ip($ip->getIp());?></td>
			<td headers="ips_libelle"><?php echo $this->escapehtml($ip->getLibelle());?></td>
			<td headers="ips_createur"><?php echo $this->escapehtml($ip->getCreateurUsername());?></td>
			<td headers="ips_machine">
				<?php if (null === $ip->getMachineId()):?>
					<em><?php echo $this->escapehtml($this->translate('Aucune machine associée'));?></em>
				<?php else: ?>
					<a href="<?php echo $this->url('machine',array('action'=>'consulter','machine'=>$ip->getMachineId()));?>"
					   title="<?php echo $this->escapehtmlattr(sprintf($this->translate('Accéder à la machine %s'),$ip->getMachineLibelle()));?>">
						<?php echo $this->escapehtml($ip->getMachineLibelle());?>
					</a>
				<?php endif;?>
			</td>
			<td headers="action">
				<div class="btn-group pull-right">
					<?php if (null !== $ip->getMachineId()):?>
					<a class="btn btn-warning btn-xs tooltip-link"
						href="<?php echo $this->url('reseau',array('action' => 'dissocierIp', 'reseau' => $this->unReseau->getId(), 'ip' => $ip->getId()));?>"
						title="<?php echo $this->escapehtmlattr($this->translate('Dissocier l\'IP de cette machine'));?>">
						<i class="fa fa-unlink"></i>
					</a>
					<?php endif;?>
					<a class="btn btn-default btn-xs tooltip-link"
						href="<?php echo $this->url('reseau',array('action' => 'associerIp', 'reseau' => $this->unReseau->getId(), 'ip' => $ip->getId()));?>"
						<?php if (null === $ip->getMachineId()):?>
						title="<?php echo $this->escapehtmlattr($this->translate('Associer à une machine'));?>">
						<?php else:?>
						title="<?php echo $this->escapehtmlattr($this->translate('Associer à une autre machine'));?>">
						<?php endif;?>
						<i class="fa fa-link"></i>
					</a>
					<a class="btn btn-danger btn-xs tooltip-link"
						href="<?php echo $this->url('reseau',array('action' => 'supprimerIp', 'reseau' => $this->unReseau->getId(), 'ip' => $ip->getId()));?>"
						title="<?php echo $this->escapehtmlattr($this->translate('Supprimer cette adresse Ip'));?>">
						<i class="fa fa-trash-o"></i>
					</a>
				</div>
			</td>
		</tr>
		<?php endforeach;?>
	</tbody>
	<tfoot>
		<tr>
			<th headers="number">#</th>
			<th headers="ips_adresse"><?php echo $this->escapehtml($this->translate('Adresse IP'));?></th>
			<th headers="ips_libelle"><?php echo $this->escapehtml($this->translate('Informations'));?></th>
			<th headers="ips_libelle"><?php echo $this->escapehtml($this->translate('Référencé par'));?></th>
			<th headers="ips_machine"><?php echo $this->escapehtml($this->translate('Machine'));?></th>
			<th headers="action"></th>
		</tr>
	</tfoot>

</table>
<?php endif;?>
