<?php $cpt = 0;?>
<div class="page-header">
	<div class="btn-grp pull-right">
		<a class="btn btn-primary tooltip-link" href="<?php echo $this->url('reseau',array('action' => 'creer'));?>" title="<?php echo $this->escapehtmlattr($this->translate('Créer un nouveau réseau'))?>">
			<i class="fa fa-sitemap fa-fw"></i>&nbsp;<?php echo $this->escapehtml($this->translate('Créer un nouveau réseau'));?>
		</a>
	</div>
	<h1>Linsting des réseaux référencés</h1>
</div>
<?php
	$flash = $this->flashmessenger();
	echo $flash->render('error',   array('alert', 'alert-dismissable', 'alert-danger'));
	echo $flash->render('warning', array('alert', 'alert-dismissable', 'alert-warning'));
	echo $flash->render('info',    array('alert', 'alert-dismissable', 'alert-info'));
	echo $flash->render('default', array('alert', 'alert-dismissable', 'alert-warning'));
	echo $flash->render('success', array('alert', 'alert-dismissable', 'alert-success'));
?>
<div class="row text-justify">
<?php if (empty($this->reseaux)):?>
	<div class="col-sm-offset-3 col-sm-6">
		<div class="panel panel-primary">
			<div class="panel-heading">
				<h2 class="panel-title">
					<i class="fa fa-info-circle"></i>
					<?php echo $this->escapehtml($this->translate('Aucun réseau'))?>
				</h2>
			</div>
			<div class="panel-body">
				<ul class="fa-ul">
					<li>
						<?php echo $this->escapehtml($this->translate("Aucun réseau n'a encore été référencé dans l'application !"))?>
					</li>
				</ul>
			</div>
			<div class="panel-footer text-center">
				<a
					class="btn btn-primary tooltip-link"
					href="<?php echo $this->url('reseau',array('action' => 'creer'));?>"
					title="<?php echo $this->escapehtmlattr($this->translate('Créer un nouveau réseau'))?>">
					<i class="fa fa-sitemap"></i>
					<?php echo $this->escapehtml($this->translate('Créer un nouveau réseau'))?>
				</a>
			</div>
		</div>
	</div>
</div>
<?php else:?>
<?php foreach ($this->reseaux as $reseau):?>
<?php //@var Reseau\Entity\View\Reseau $reseau ?>
<?php if ($cpt % 2 == 0):?>
<div class="row">
<?php endif;?>
	<?php $couleur = sprintf('style="color:#%s"',$this->escapehtmlattr($reseau->getCouleur()));?>
	<div class="col-sm-6">
		<div class="panel panel-default">
			<div class="panel-heading">
				<h2 class="panel-title text-center">
					<i <?php echo $couleur;?> class="fa fa-quote-left pull-left"></i>
						<?php echo $this->escapehtml($reseau->getLibelle());?>
					<i <?php echo $couleur;?> class="fa fa-quote-right pull-right"></i>
				</h2>
			</div>
			<div class="panel-body">
				<i class="fa fa-sitemap fa-2x fa-border pull-left" <?php echo $couleur;?>></i>
				<div class="progress">
					<?php $pourcentage = $this->escapehtmlattr(sprintf('%.0f',$reseau->getIpPourcentageOccupe()));?>
					<?php
						if( $reseau->getIpPourcentageOccupe() < 60){
							$couleurBar = 'progress-bar-success';
						}elseif($reseau->getIpPourcentageOccupe()<80){
							$couleurBar = 'progress-bar-warning';
						}else {
							$couleurBar = 'progress-bar-danger';
						}
					?>
  					<div class="progress-bar <?php echo $couleurBar;?> progress-bar-striped" role="progressbar" aria-valuenow="<?php echo $pourcentage;?>" aria-valuemin="0" aria-valuemax="100">
    					<?php echo $pourcentage?>%
  					</div>
				</div>
				<div class="clearfix "></div>
				<dl class="dl-horizontal">
	  				<dt><?php echo $this->translate('Description');?>&nbsp;:</dt>
	  				<dd><?php echo $this->escapehtml($reseau->getDescription());?></dd>
				</dl>
				<dl class="dl-horizontal">
	  				<dt><?php echo $this->translate('Réseau');?>&nbsp;:</dt>
	  				<dd><?php echo $this->escapehtml($reseau->getCIDR());?></dd>
				</dl>
				<dl class="dl-horizontal">
	  				<dt><?php echo $this->translate('Masque');?>&nbsp;:</dt>
	  				<dd><?php echo $this->escapehtml($reseau->getMasque());?></dd>
				</dl>
				<dl class="dl-horizontal">
	  				<dt><?php echo $this->translate('Broadcast');?>&nbsp;:</dt>
	  				<dd><?php echo $this->escapehtml($reseau->getBroadcast());?></dd>
				</dl>
				<dl class="dl-horizontal">
	  				<dt><?php echo $this->translate('Passerelle');?>&nbsp;:</dt>
	  				<dd><?php echo $this->escapehtml($reseau->getPasserelle());?></dd>
				</dl>
				<dl class="dl-horizontal">
	  				<dt><?php echo $this->translate('Occupations IP');?>&nbsp;:</dt>
	  				<dd><abbr title="<?php echo $this->escapehtmlattr(sprintf($this->translate('%d adresses IP occupées sur %d adresses théoriquement disponibles'),$reseau->getQuantiteIp(),$reseau->getIpTheoriquementDisponible()));?>"><?php echo sprintf('%d / %d',$reseau->getQuantiteIp(),$reseau->getIpTheoriquementDisponible())?></abbr>
				</dl>
			</div>
			<div class="panel-footer text-right">
				<div class="btn-group">
					<a class="btn btn-default tooltip-link" href="<?php echo $this->url('reseau',array('action' => 'reserverIp','reseau' => $reseau->getId()));?>" title="<?php echo $this->escapehtml($this->translate('Réserver une adresse IP de ce réseau'));?>"><i class="fa fa-plus"></i></a>
					<a class="btn btn-default tooltip-link" href="<?php echo $this->url('reseau',array('action' => 'consulter','reseau' => $reseau->getId()));?>" title="<?php echo $this->escapehtml($this->translate('Consulter ce réseau'));?>"><i class="fa fa-search"></i></a>
					<a class="btn btn-danger tooltip-link <?php echo ($reseau->getQuantiteIP())?' disabled ':'';?>" href="<?php echo $this->url('reseau',array('action' => 'supprimer','reseau' => $reseau->getId()));?>" title="<?php echo $this->escapehtml($this->translate('Supprimer ce réseau'));?>"><i class="fa fa-trash-o"></i></a>
				</div>
			</div>
		</div>
	</div>
<?php if ($cpt++ % 2 || $reseau == end($reseaux)):?>
</div>
<?php endif;?>
<?php endforeach;?>
<div class="btn-grp pull-right">
	<a class="btn btn-primary tooltip-link" href="<?php echo $this->url('reseau',array('action' => 'creer'));?>" title="<?php echo $this->escapehtmlattr($this->translate('Créer un nouveau réseau'))?>">
		<i class="fa fa-sitemap fa-fw"></i>&nbsp;<?php echo $this->escapehtml($this->translate('Créer un nouveau réseau'));?>
	</a>
</div>
<?php endif;?>