<?php $routeParams = $this->routeParams; ?>
<?php if ($this->pageCount): ?>
     <div>
         <ul class="pagination pagination-sm">
             <!-- Previous page link -->
             <?php if (isset($this->previous)): ?>
             	 <?php $routeParams['page']=$this->first; ?>
                 <li>
                     <a href="<?php echo $this->url($this->route,$routeParams); ?>">
                         <i class="fa fa-fw fa-angle-double-left"></i>
                     </a>
                 </li>
                 <?php $routeParams['page']=$this->previous; ?>
                 <li>
                     <a href="<?php echo $this->url($this->route,$routeParams); ?>">
                         <i class="fa fa-fw fa-angle-left"></i>
                     </a>
                 </li>
             <?php else: ?>
                 <li class="disabled">
                     <a href="#">
                         <i class="fa fa-fw fa-angle-double-left"></i>
                     </a>
                 </li>
                 <li class="disabled">
                     <a href="#">
                         <i class="fa fa-fw fa-angle-left"></i>
                     </a>
                 </li>
                 <?php endif; ?>

             <!-- Numbered page links -->
             <?php foreach ($this->pagesInRange as $page): ?>
                 <?php $routeParams['page'] = $page; ?>
                 <?php if ($page != $this->current): ?>
                     <li>
                         <a href="<?php echo $this->url($this->route,$routeParams); ?>">
                             <?php echo $page; ?>
                         </a>
                     </li>
                 <?php else: ?>
                     <li class="active">
                         <a href="#"><?php echo $page; ?></a>
                     </li>
                 <?php endif; ?>
             <?php endforeach; ?>

             <!-- Next page link -->
             <?php if (isset($this->next)): ?>
             	 <?php $routeParams['page']=$this->next; ?>
                 <li>
                     <a href="<?php echo $this->url($this->route,$routeParams); ?>">
                         <i class="fa fa-fw fa-angle-right"></i>
                     </a>
                 </li>
                 <?php $routeParams['page']=$this->last; ?>
                 <li>
                     <a href="<?php echo $this->url($this->route,$routeParams); ?>">
                         <i class="fa fa-fw fa-angle-double-right"></i>
                     </a>
                 </li>
             <?php else: ?>
                 <li class="disabled">
                     <a href="#">
                         <i class="fa fa-fw fa-angle-right"></i>
                     </a>
                 </li>
                 <li class="disabled">
                     <a href="#">
                         <i class="fa fa-fw fa-angle-double-right"></i>
                     </a>
                 </li>
             <?php endif; ?>
         </ul>
     </div>
 <?php endif; ?>