<?php if ($this->pageCount): ?>
     <div>
         <ul class="pagination">
             <!-- Previous page link -->
             <?php if (isset($this->previous)): ?>
                 <li>
                     <a href="<?php echo $this->url($this->route,['page' => $this->previous, 'itemsPerPage' => $this->itemsPerPage , 'sort' => $this->sort]); ?>">
                         <i class="fa fa-fw fa-angle-double-left"></i>
                     </a>
                 </li>
             <?php else: ?>
                 <li class="disabled">
                     <a href="#">
                         <i class="fa fa-fw fa-angle-double-left"></i>
                     </a>
                 </li>
             <?php endif; ?>

             <!-- Numbered page links -->
             <?php foreach ($this->pagesInRange as $page): ?>
                 <?php if ($page != $this->current): ?>
                     <li>
                         <a href="<?php echo $this->url($this->route,['page' => $page, 'itemsPerPage' => $this->itemsPerPage , 'sort' => $this->sort]); ?>">
                             <?php echo $page; ?>
                         </a>
                     </li>
                 <?php else: ?>
                     <li class="active">
                         <a href="#"><?php echo $page; ?></a>
                     </li>
                 <?php endif; ?>
             <?php endforeach; ?>

             <!-- Next page link -->
             <?php if (isset($this->next)): ?>
                 <li>
                     <a href="<?php echo $this->url($this->route,['page' => $this->next, 'itemsPerPage' => $this->itemsPerPage , 'sort' => $this->sort]); ?>">
                         <i class="fa fa-fw fa-angle-double-right"></i>
                     </a>
                 </li>
             <?php else: ?>
                 <li class="disabled">
                     <a href="#">
                         <i class="fa fa-fw fa-angle-double-right"></i>
                     </a>
                 </li>
             <?php endif; ?>
         </ul>
     </div>
 <?php endif; ?>