<?php
// Generated by Zend Framework 2
return array(
    'Administration\Controller\IndexController' => __DIR__ . '/src/Administration/Controller/IndexController.php',
    'Administration\Controller\UserController'  => __DIR__ . '/src/Administration/Controller/UserController.php',
    'Administration\Controller\RoleController'  => __DIR__ . '/src/Administration/Controller/RoleController.php',
    'Administration\Module'                     => __DIR__ . '/Module.php',
);