<?php
    $page = $this->page;
    $itemsPerPage = $this->itemsPerPage;
?>
<h1><?php echo $this->escapeHtml($this->translate('Listing des utilisateurs'));?></h1>
<?php if (count($this->paginator)): ?>
<table class="table table-bordered table-hover table-responsive">
    <thead>
        <tr>
            <th id="identifiants">
                <?php echo $this->escapeHtml($this->translate('Identifiant'));?>
                <span class="btn-group pull-right">
                    <a class="btn btn-xs <?php echo ('IdAsc' == $this->sort)?'active btn-primary':'btn-default'; ?>" 
                        href="<?php echo $this->url('zfcadmin/user',['page' => $page, 'itemsPerPage' => $itemsPerPage,'sort' => 'IdAsc']);?>" 
                       title="<?php echo $this->escapehtmlattr($this->translate('Sort users by id ascending'))?>">
                        <i class="fa fa-fw fa-sort-numeric-asc"></i>
                    </a>
                    <a class="btn btn-xs <?php echo ('IdDesc' == $this->sort)?'active btn-primary':'btn-default'; ?>" 
                        href="<?php echo $this->url('zfcadmin/user',['page' => $page, 'itemsPerPage' => $itemsPerPage,'sort' => 'IdDesc']);?>" 
                       title="<?php echo $this->escapehtmlattr($this->translate('Sort users by id descending'))?>">
                        <i class="fa fa-fw fa-sort-numeric-desc"></i>
                    </a>
                </span>
            </th>
            <th id="names">
                <?php echo $this->escapeHtml($this->translate('Username'));?>
                <span class="btn-group pull-right">
                    <a class="btn btn-xs <?php echo ('UsernameAsc' == $this->sort)?'active btn-primary':'btn-default'; ?>" 
                        href="<?php echo $this->url('zfcadmin/user',['page' => $page, 'itemsPerPage' => $itemsPerPage,'sort' => 'UsernameAsc']);?>" 
                       title="<?php echo $this->escapehtmlattr($this->translate('Sort users by username ascending'))?>">
                        <i class="fa fa-fw fa-sort-alpha-asc"></i>
                    </a>
                    <a class="btn btn-xs <?php echo ('UsernameDesc' == $this->sort)?'active btn-primary':'btn-default'; ?>" 
                        href="<?php echo $this->url('zfcadmin/user',['page' => $page, 'itemsPerPage' => $itemsPerPage,'sort' => 'UsernameDesc']);?>" 
                       title="<?php echo $this->escapehtmlattr($this->translate('Sort users by username descending'))?>">
                        <i class="fa fa-fw fa-sort-alpha-desc"></i>
                    </a>
                </span>
            </th>
            <th id="emails">
                <?php echo $this->escapeHtml($this->translate('Email'));?>
                <span class="btn-group pull-right">
                    <a class="btn btn-xs <?php echo ('EmailAsc' == $this->sort)?'active btn-primary':'btn-default'; ?>" 
                        href="<?php echo $this->url('zfcadmin/user',['page' => $page, 'itemsPerPage' => $itemsPerPage,'sort' => 'EmailAsc']);?>" 
                       title="<?php echo $this->escapehtmlattr($this->translate('Sort users by email ascending'))?>">
                        <i class="fa fa-fw fa-sort-alpha-asc"></i>
                    </a>
                    <a class="btn btn-xs <?php echo ('EmailDesc' == $this->sort)?'active btn-primary':'btn-default'; ?>" 
                        href="<?php echo $this->url('zfcadmin/user',['page' => $page, 'itemsPerPage' => $itemsPerPage,'sort' => 'EmailDesc']);?>" 
                       title="<?php echo $this->escapehtmlattr($this->translate('Sort users by email descending'))?>">
                        <i class="fa fa-fw fa-sort-alpha-desc"></i>
                    </a>
                </span>
            </th>
            <th id="display_names">
                <?php echo $this->escapeHtml($this->translate('Display Name'));?>
                <span class="btn-group pull-right">
                    <a class="btn btn-xs <?php echo ('DisplayNameAsc' == $this->sort)?'active btn-primary':'btn-default'; ?>" 
                        href="<?php echo $this->url('zfcadmin/user',['page' => $page, 'itemsPerPage' => $itemsPerPage,'sort' => 'DisplayNameAsc']);?>" 
                       title="<?php echo $this->escapehtmlattr($this->translate('Sort users by display name ascending'))?>">
                        <i class="fa fa-fw fa-sort-alpha-asc"></i>
                    </a>
                    <a class="btn btn-xs <?php echo ('DisplayNameDesc' == $this->sort)?'active btn-primary':'btn-default'; ?>" 
                        href="<?php echo $this->url('zfcadmin/user',['page' => $page, 'itemsPerPage' => $itemsPerPage,'sort' => 'DisplayNameDesc']);?>" 
                       title="<?php echo $this->escapehtmlattr($this->translate('Sort users by display name descending'))?>">
                        <i class="fa fa-fw fa-sort-alpha-desc"></i>
                    </a>
                </span>
            </th>
            <th id="actions"></th>
        </tr>        
    </thead>
    <tbody>
        <?php foreach ($this->paginator as $user):?>
        <tr>
            <td headers="identifiants"><?php echo $this->escapeHtml($user->getId());?></td>
            <td headers="names"><?php echo $this->escapeHtml($user->getUsername());?></td>
            <td headers="emails"><?php echo $this->escapeHtml($user->getEmail());?></td>
            <td headers="display_names"><?php echo $this->escapeHtml($user->getDisplayName());?></td>
            <td headers="actions">
                <span class="btn-group">
                <?php if ($this->viewIsAllowed):?>
                    <a class="btn btn-default btn-xs" href="#" title="<?php echo $this->escapehtmlattr('View');?>">
                        <i class="fa fa-fw fa-eye"></i>
                    </a>
                <?php endif;?>
                <?php if ($this->editIsAllowed):?>
                    <a class="btn btn-default btn-xs" href="#" title=<?php echo $this->escapehtmlattr('Edit');?>>
                        <i class="fa fa-fw fa-pencil"></i>
                    </a>
                <?php endif;?>
                <?php if ($this->deleteIsAllowed):?>
                    <a class="btn btn-default btn-xs" href="#" title=<?php echo $this->escapehtmlattr('Delete');?>>
                        <i class="fa fa-fw fa-trash-o"></i>
                    </a>
                <?php endif;?>
                </span>
            </td>
        </tr>
        <?php endforeach;?>
    </tbody>
</table>
<div class="text-center">
    <?php echo $this->paginationControl($this->paginator,
                                    'sliding',
                                    'partial/paginator.phtml', 
                                    array(
                                        'route' => 'zfcadmin/user',
                                        'itemsPerPage' => $itemsPerPage,
                                        'sort'       => $this->sort,
                                    )); ?>
</div>
<?php else: //Aucun utilisateur?>
<div class="alert alert-info">Aucun utilisateur</div>
<?php endif;?>