<?php
    use TwbBundle\Form\View\Helper\TwbBundleForm;
    
    //Simplification
    $page = $this->page;
    $itemsPerPage = $this->itemsPerPage;
    $sort = $this->sort;
    $searchText = $this->searchText;
    
    //Gravatars Settings
    $settings = array(
        'img_size'    => 16,
        'default_img' => \Zend\View\Helper\Gravatar::DEFAULT_IDENTICON,
        'rating'      => \Zend\View\Helper\Gravatar::RATING_G,
        'secure'      => null,
    );
    $attr = ['class'=>'gravatar'];
    
    //dateFormat
    $zfcUser = $this->zfcUserIdentity();
    if ($zfcUser){
        $this->plugin('dateFormat')->setTimeZone($zfcUser->getTimeZone())->setLocale($zfcUser->getLocale());
    }
    
    //Paginator
    $paginator = $this->paginationControl($this->paginator,
        'sliding',
        'partial/paginator.phtml',
        [
            'route'        => 'zfcadmin/user',
            'routeParams'  => [
                'itemsPerPage' => $itemsPerPage,
                'sort'         => $sort,
                'search'   => $searchText
            ],
        ]);
    
    //Fonction pour la liste déroulante
    $jsMultiplicateur = $this->escapejs($page * $itemsPerPage);
    $jsSort = $this->escapejs($sort);
    $jsUrl  = $this->escapejs($this->url('zfcadmin/user'));
    $jsSearchText = $this->escapejs($searchText);
    $jsVarSearchText = empty($searchText)?'':"var searchText = '$jsSearchText';";
    $jsSearchUrl = empty($searchText)?'':" + '?search=$jsSearchText'";
    $this->headscript()->appendScript("function changement(){
    	var items = \$('#selectItemsPerPage').val();
    	var page  = Math.ceil($jsMultiplicateur / items);
    	var sort  = '$jsSort';
    	var route = '$jsUrl'; 	
        $jsVarSearchText
    	$(location).attr('href',route + '/page' + page + '/itemsPerPage' + items + '/sortBy'+ sort $jsSearchUrl);	
    }");
   
?>
<div class="page-header">
    <h1>
        <?php echo $this->escapeHtml($this->translate('Listing des utilisateurs'));?>
    </h1>
</div>
<div class="row">
    <div class="col-sm-8">
        <?php echo $paginator; ?>
    </div>
    <div class="col-sm-4">
        <div class="pull-right pagination">
            <?php echo $this->form($this->searchForm,TwbBundleForm::LAYOUT_INLINE)?>
        </div>
    </div>
</div>
<div class="flashmessenger">
<?php
    
	$flash = $this->flashmessenger();
	echo $flash->render('error',   array('alert', 'alert-dismissable', 'alert-danger'));
	echo $flash->render('warning', array('alert', 'alert-dismissable', 'alert-warning'));
	echo $flash->render('info',    array('alert', 'alert-dismissable', 'alert-info'));
	echo $flash->render('default', array('alert', 'alert-dismissable', 'alert-warning'));
	echo $flash->render('success', array('alert', 'alert-dismissable', 'alert-success'));
?>
</div>
<?php if (count($this->paginator)): ?>
<div class="table-responsive">
<table class="table table-bordered table-hover table-responsive table-striped">
    <thead>
        <tr>
            <th id="identifiants">
                <?php echo $this->escapeHtml($this->translate('Identifiant'));?>
                <span class="btn-group pull-right">
                    <a class="btn btn-xs <?php echo ('IdAsc' == $this->sort)?'active btn-primary':'btn-default'; ?>" 
                        href="<?php echo $this->url('zfcadmin/user',['page' => $page, 'itemsPerPage' => $itemsPerPage,'sort' => 'IdAsc','search' => $searchText]);?>" 
                       title="<?php echo $this->escapehtmlattr($this->translate('Sort users by id ascending'))?>">
                        <i class="fa fa-fw fa-sort-numeric-asc"></i>
                    </a>
                    <a class="btn btn-xs <?php echo ('IdDesc' == $this->sort)?'active btn-primary':'btn-default'; ?>" 
                        href="<?php echo $this->url('zfcadmin/user',['page' => $page, 'itemsPerPage' => $itemsPerPage,'sort' => 'IdDesc','search' => $searchText]);?>" 
                       title="<?php echo $this->escapehtmlattr($this->translate('Sort users by id descending'))?>">
                        <i class="fa fa-fw fa-sort-numeric-desc"></i>
                    </a>
                </span>
            </th>
            <th id="names">
                <?php echo $this->escapeHtml($this->translate('Username'));?>
                <span class="btn-group pull-right">
                    <a class="btn btn-xs <?php echo ('UsernameAsc' == $this->sort)?'active btn-primary':'btn-default'; ?>" 
                        href="<?php echo $this->url('zfcadmin/user',['page' => $page, 'itemsPerPage' => $itemsPerPage,'sort' => 'UsernameAsc','search' => $searchText]);?>" 
                       title="<?php echo $this->escapehtmlattr($this->translate('Sort users by username ascending'))?>">
                        <i class="fa fa-fw fa-sort-alpha-asc"></i>
                    </a>
                    <a class="btn btn-xs <?php echo ('UsernameDesc' == $this->sort)?'active btn-primary':'btn-default'; ?>" 
                        href="<?php echo $this->url('zfcadmin/user',['page' => $page, 'itemsPerPage' => $itemsPerPage,'sort' => 'UsernameDesc','search' => $searchText]);?>" 
                       title="<?php echo $this->escapehtmlattr($this->translate('Sort users by username descending'))?>">
                        <i class="fa fa-fw fa-sort-alpha-desc"></i>
                    </a>
                </span>
            </th>
            <th id="emails">
                <?php echo $this->escapeHtml($this->translate('Email'));?>
                <span class="btn-group pull-right">
                    <a class="btn btn-xs <?php echo ('EmailAsc' == $this->sort)?'active btn-primary':'btn-default'; ?>" 
                        href="<?php echo $this->url('zfcadmin/user',['page' => $page, 'itemsPerPage' => $itemsPerPage,'sort' => 'EmailAsc','search' => $searchText]);?>" 
                       title="<?php echo $this->escapehtmlattr($this->translate('Sort users by email ascending'))?>">
                        <i class="fa fa-fw fa-sort-alpha-asc"></i>
                    </a>
                    <a class="btn btn-xs <?php echo ('EmailDesc' == $this->sort)?'active btn-primary':'btn-default'; ?>" 
                        href="<?php echo $this->url('zfcadmin/user',['page' => $page, 'itemsPerPage' => $itemsPerPage,'sort' => 'EmailDesc','search' => $searchText]);?>" 
                       title="<?php echo $this->escapehtmlattr($this->translate('Sort users by email descending'))?>">
                        <i class="fa fa-fw fa-sort-alpha-desc"></i>
                    </a>
                </span>
            </th>
            <th id="display_names">
                <?php echo $this->escapeHtml($this->translate('Display Name'));?>
                <span class="btn-group pull-right">
                    <a class="btn btn-xs <?php echo ('DisplayNameAsc' == $this->sort)?'active btn-primary':'btn-default'; ?>" 
                        href="<?php echo $this->url('zfcadmin/user',['page' => $page, 'itemsPerPage' => $itemsPerPage,'sort' => 'DisplayNameAsc','search' => $searchText]);?>" 
                       title="<?php echo $this->escapehtmlattr($this->translate('Sort users by display name ascending'))?>">
                        <i class="fa fa-fw fa-sort-alpha-asc"></i>
                    </a>
                    <a class="btn btn-xs <?php echo ('DisplayNameDesc' == $this->sort)?'active btn-primary':'btn-default'; ?>" 
                        href="<?php echo $this->url('zfcadmin/user',['page' => $page, 'itemsPerPage' => $itemsPerPage,'sort' => 'DisplayNameDesc','search' => $searchText]);?>" 
                       title="<?php echo $this->escapehtmlattr($this->translate('Sort users by display name descending'))?>">
                        <i class="fa fa-fw fa-sort-alpha-desc"></i>
                    </a>
                </span>
            </th>
            <th id="inscriptions">
                <?php echo $this->escapeHtml($this->translate('Inscription'));?>
                <span class="btn-group pull-right">
                    <a class="btn btn-xs <?php echo ('InscriptionAsc' == $this->sort)?'active btn-primary':'btn-default'; ?>" 
                        href="<?php echo $this->url('zfcadmin/user',['page' => $page, 'itemsPerPage' => $itemsPerPage,'sort' => 'InscriptionAsc','search' => $searchText]);?>" 
                       title="<?php echo $this->escapehtmlattr($this->translate('Sort users by inscription date ascending'))?>">
                        <i class="fa fa-fw fa-sort-alpha-asc"></i>
                    </a>
                    <a class="btn btn-xs <?php echo ('InscriptionDesc' == $this->sort)?'active btn-primary':'btn-default'; ?>" 
                        href="<?php echo $this->url('zfcadmin/user',['page' => $page, 'itemsPerPage' => $itemsPerPage,'sort' => 'InscriptionDesc','search' => $searchText]);?>" 
                       title="<?php echo $this->escapehtmlattr($this->translate('Sort users by inscription date descending'))?>">
                        <i class="fa fa-fw fa-sort-alpha-desc"></i>
                    </a>
                </span>
            </th>
            <th id="lastsvisite">
                <?php echo $this->escapeHtml($this->translate('Dernière visite'));?>
                <span class="btn-group pull-right">
                    <a class="btn btn-xs <?php echo ('LastVisiteAsc' == $this->sort)?'active btn-primary':'btn-default'; ?>" 
                        href="<?php echo $this->url('zfcadmin/user',['page' => $page, 'itemsPerPage' => $itemsPerPage,'sort' => 'LastVisiteAsc','search' => $searchText]);?>" 
                       title="<?php echo $this->escapehtmlattr($this->translate('Sort users by last visite date ascending'))?>">
                        <i class="fa fa-fw fa-sort-amount-asc"></i>
                    </a>
                    <a class="btn btn-xs <?php echo ('LastVisiteDesc' == $this->sort)?'active btn-primary':'btn-default'; ?>" 
                        href="<?php echo $this->url('zfcadmin/user',['page' => $page, 'itemsPerPage' => $itemsPerPage,'sort' => 'LastVisiteDesc','search' => $searchText]);?>" 
                       title="<?php echo $this->escapehtmlattr($this->translate('Sort users by last visite date descending'))?>">
                        <i class="fa fa-fw fa-sort-amount-desc"></i>
                    </a>
                </span>
            </th>
            <th id="actions"></th>
        </tr>        
    </thead>
    <tbody>
        <?php foreach ($this->paginator as $user):?>
        <tr>
            <td headers="identifiants"><?php echo $this->escapeHtml($user->getId());?></td>
            <td headers="names"><?php echo $this->escapeHtml($user->getUsername());?></td>
            <td headers="emails">
                <?php echo $this->gravatar($user->getEmail(),$settings,$attr);?>
                <?php echo $this->escapeHtml($user->getEmail());?>
            </td>
            <td headers="display_names"><?php echo $this->escapeHtml($user->getDisplayName());?></td>            
            <td headers="inscriptions"><?php echo $this->dateFormat($user->getInscription(),IntlDateFormatter::MEDIUM,IntlDateFormatter::MEDIUM);?></td>
            <td headers="lastsvisit"><?php echo $this->dateFormat($user->getLastVisite(),IntlDateFormatter::MEDIUM,IntlDateFormatter::MEDIUM);?></td>
            <td headers="actions">
                <span class="btn-group">
                <?php if ($this->viewIsAllowed):?>
                    <a class="btn btn-default btn-xs" 
                        href="<?php echo $this->url('zfcadmin/user',['action'=>'active','user'=>$user->getId()]);?>" 
                       title="<?php echo $this->escapehtmlattr('View');?>">
                        <i class="fa fa-fw fa-eye"></i>
                    </a>
                <?php endif;?>
                <?php if ($this->editIsAllowed):?>
                    <a class="btn btn-default btn-xs" href="#" title=<?php echo $this->escapehtmlattr('Edit');?>>
                        <i class="fa fa-fw fa-pencil"></i>
                    </a>
                <?php endif;?>
                <?php if ($this->activatingIsAllowed):?>
                    <a class="btn btn-default btn-xs <?php echo ($user->isActive())?'disabled':'';?>" 
                        href="<?php echo $this->url('zfcadmin/user',['action'=>'active','user'=>$user->getId()]);?>" 
                       title=<?php echo $this->escapehtmlattr('Active');?>>
                        <i class="fa fa-fw fa-check"></i>
                    </a>
                <?php endif;?>
                <?php if ($this->banIsAllowed):?>
                    <a class="btn btn-default btn-xs" href="#" title=<?php echo $this->escapehtmlattr('Ban');?>>
                        <i class="fa fa-fw fa-ban"></i>
                    </a>
                <?php endif;?>
                <?php if ($this->deleteIsAllowed):?>
                    <a class="btn btn-default btn-xs" href="#" title=<?php echo $this->escapehtmlattr('Delete');?>>
                        <i class="fa fa-fw fa-trash-o"></i>
                    </a>
                <?php endif;?>
                </span>
                <?php if ($user->isBanned()):?>
                    <span class="label label-danger"><?php echo $this->escapehtml($this->translate('Banned'))?></span>
                <?php elseif (!$user->isActive()):?>
                    <span class="label label-warning"><?php echo $this->escapehtml($this->translate('Inactive'))?></span>
                <?php endif;?>
            </td>
        </tr>
        <?php endforeach;?>
    </tbody>    
    <caption>
        <?php if (empty($searchText)):?>
            <?php echo $this->escapehtml(sprintf($this->translatePlural('%s utilisateur enregistré', '%s utilisateurs enregistrés', $this->paginator->getTotalItemCount()),$this->paginator->getTotalItemCount()));?>
        <?php else:?>
            <?php echo $this->escapehtml(sprintf($this->translatePlural('%s utilisateur correspond à votre recherche', '%s utilisateurs correspondent à votre recherche', $this->paginator->getTotalItemCount()),$this->paginator->getTotalItemCount()));?>
        <?php endif;?>
    </caption>
        
</table>
</div>
<div class="row">
    <div class="col-sm-8">    
        <?php echo $paginator; ?>
    </div>
    <div class="col-sm-4">
        <div class="text-right pagination">
            <?php echo $this->formElement($this->ioSelect);?>
        </div>
    </div>
</div>
<?php else: //Aucun utilisateur?>
<div class="alert alert-info">Aucun utilisateur</div>
<?php endif;?>