<div class="page-header">
	<h1>
	   <i class="fa fa-fw fa-eye"></i>
		<?php echo sprintf($this->escapehtml($this->translate('Informations détaillées de %s')),
			              '<strong>'.$this->escapehtml($this->user->getEmail()).'</strong>');
	    ?>
	    <?php if ($this->user->isBanned()):?>
	       <span class="pull-right label label-danger"><?php echo $this->escapeHtml('Banned user')?></span>
	    <?php endif;?>
	    <?php if (!$this->user->isActive()):?>
	       <span class="pull-right label label-warning"><?php echo $this->escapeHtml('Unactivated user')?></span>
	    <?php endif;?>
	</h1>
</div>
<?php
	$flash = $this->flashmessenger();
	echo $flash->render('error',   array('alert', 'alert-dismissable', 'alert-danger'));
	echo $flash->render('warning', array('alert', 'alert-dismissable', 'alert-warning'));
	echo $flash->render('info',    array('alert', 'alert-dismissable', 'alert-info'));
	echo $flash->render('default', array('alert', 'alert-dismissable', 'alert-warning'));
	echo $flash->render('success', array('alert', 'alert-dismissable', 'alert-success'));
?>
<div class="row text-justify">
	<div class="col-sm-6 col-lg-4">
		<div class="panel panel-primary">
			<div class="panel-heading">
				<h2 class="panel-title">
				    <i class="fa fa-fw fa-eye"></i>
					<?php echo $this->translate('General information about this user');?>
				</h2>
			</div>
			<div class="panel-body">
				<dl class="dl-horizontal">
					<dt><?php echo $this->translate('Username');?></dt>
					<dd><?php echo $this->escapehtml($this->user->getUsername());?></dd>
				</dl>
				<dl class="dl-horizontal">
					<dt><?php echo $this->translate('Display Name');?></dt>
					<dd><?php echo $this->escapehtml($this->user->getDisplayName());?></dd>
				</dl>
				<dl class="dl-horizontal">
					<dt><?php echo $this->translate('Email');?></dt>
					<dd><?php echo $this->escapehtml($this->user->getEmail());?></dd>
				</dl>
			</div>
		</div>
	</div>
	<div class="col-sm-6 col-lg-4">
	   <div class="panel panel-default">
			<div class="panel-heading">
				<h2 class="panel-title">
				    <i class="fa fa-fw fa-calendar"></i>
					<?php echo $this->translate('Calendrier');?>
				</h2>
			</div>
			<div class="panel-body">
				<dl class="dl-horizontal">
					<dt><?php echo $this->translate('Registration date');?></dt>
					<dd><?php echo $this->dateFormat($this->user->getInscription(),IntlDateFormatter::SHORT,IntlDateFormatter::SHORT);?></dd>
				</dl>
				<dl class="dl-horizontal">
					<dt><?php echo $this->translate('Activation date');?></dt>					
					<dd>
					   <?php if ($this->user->isActive()):?>
					   <?php echo $this->dateFormat($this->user->getActivation(),IntlDateFormatter::SHORT,IntlDateFormatter::SHORT);?>
					   <?php else:?>
					   <span class="label label-warning"><?php echo $this->escapeHtml('Unactivated user')?></span>
					   <?php endif;?>
					</dd>
				</dl>
				<dl class="dl-horizontal">
					<dt><?php echo $this->translate('Last activity');?></dt>
					<dd><?php echo $this->dateFormat($this->user->getLastVisite(),IntlDateFormatter::SHORT,IntlDateFormatter::SHORT);?></dd>
				</dl>
				<dl class="dl-horizontal">
					<dt><?php echo $this->translate('Last update');?></dt>
					<dd><?php echo $this->dateFormat($this->user->getModification(),IntlDateFormatter::SHORT,IntlDateFormatter::SHORT);?></dd>
				</dl>
				<dl class="dl-horizontal">
					<dt><?php echo $this->translate('Date du bannissement');?></dt>					
					<dd>
					   <?php if ($this->user->isBanned()):?>
					   <?php echo $this->dateFormat($this->user->getBannissement(),IntlDateFormatter::SHORT,IntlDateFormatter::SHORT);?>
					   <?php else:?>
					   <span class="label label-default"><?php echo $this->escapeHtml('Not banned account')?></span>
					   <?php endif;?>
					</dd>
				</dl>
			</div>
		</div>
	</div>
	<div class="col-sm-6 col-lg-4">
	   <div class="panel panel-default">
			<div class="panel-heading">
				<h2 class="panel-title">
				    <i class="fa fa-fw fa-wrench"></i>
					<?php echo $this->translate('Administration tools');?>
				</h2>
			</div>
			<div class="panel-body">
			    <?php if ($this->unbanIsAllowed && $this->user->isBanned()):?>
    				<a class="btn btn-lg btn-default" 
    				    href="<?php echo $this->url('zfcadmin/user',['action'=>'unban','user'=>$this->user->getId()]);?>"
    				    title="<?php echo $this->escapehtmlattr($this->translate('Unban this user'))?>">
                        <span class="fa-stack fa-lg">
                            <i class="fa fa-camera fa-user-1x"></i>
                            <i class="fa fa-ban fa-stack-2x text-success"></i>
                        </span> 
                        <?php echo $this->escapehtml($this->translate('Unban'));?>
                    </a>
                <?php elseif ($this->banIsAllowed && !$this->user->isBanned()):?>
                    <a class="btn btn-lg btn-default" 
                       title="<?php echo $this->escapehtmlattr($this->translate('Ban this user'))?>"
    				    href="<?php echo $this->url('zfcadmin/user',['action'=>'ban','user'=>$this->user->getId()]);?>">
                        <span class="fa-stack fa-lg">
                            <i class="fa fa-camera fa-user-1x"></i>
                            <i class="fa fa-ban fa-stack-2x text-danger"></i>
                        </span> 
                        <?php echo $this->escapehtml($this->translate('Ban'));?>
                    </a>
                <?php endif?>
                <?php if ($this->editIsAllowed):?>
                    <a class="btn btn-lg btn-default"
                        href="<?php echo $this->url('zfcadmin/user',['action'=>'edit','user'=>$this->user->getId()]);?>"
                       title="<?php echo $this->escapehtmlattr($this->translate('Edit this user'));?>">
                       <i class="fa fa-lg fa-stack fa-pencil"></i>
                       <?php echo $this->escapehtml($this->translate('Edit'));?>
                    </a>
                <?php endif;?>
			</div>
		</div>
	</div>
</div>