<?php
/**
 * GMAO - GMAO Application Zend Framework 2 User Module
 *
 * @link https://github.com/Alexandre-T/gmao for the canonical source repository
 * @copyright Copyright (c) 2005-${year} Alexandre Tranchant
 * @license https://github.com/Alexandre-T/gmao/blob/master/LICENSE MIT
 * @author Alexandre Tranchant <Alexandre.Tranchant@gmail.com>
 */

echo $this->partial('csn-user/layout/nav-menu',
		array('navMenu' => $this->navMenu, 'user' => $this->identity()));

?>

<div class="jumbotron">
	<h1><?php echo $this->error;?></h1>
	<p><?php echo $this->messages;?></p>
	<p class="btn-group">
		<a class="btn btn-default" href="<?php echo $this->url('user-index',array('action' => 'logout')); ?>">
			<i class="fa fa-sign-out"></i>&nbsp;<?php echo $this->escapehtml($this->translate('Log Out'))?>
		</a>
	</p>
</div>
