<div class="page-header">
<h1>Les fonctions d'IP-Trevise</h1>
</div>
<div class="row text-justify">
	<div class="col-sm-6">
		<div class="panel panel-primary">
			<div class="panel-heading">
				<h2 class="panel-title">Fonctionnalités générales</h2>
			</div>
			<div class="panel-body">
				<p>
					L'application permet aux administrateur de gérer leurs
					adresses IP, leurs réseaux et les machines associées à
					ceux-ci.
				</p>
			</div>
			<div class="panel-footer">
				<ul class="list-unstyled">
					<li><i class="fa fa-sitemap fa-fw"></i>&nbsp;Gestion des réseaux d'adresse IP et leur plage</li>
					<li><i class="fa fa-share-alt fa-fw"></i>&nbsp;Gestion des réservations d'adresse IP</li>
					<li><i class="fa fa-desktop fa-fw"></i>&nbsp;Gestion des «&nbsp;machines&nbsp;» comprenant les postes bureautiques, les serveurs, les routeurs, etc...</li>
				</ul>
			</div>
		</div>
	</div>
	<div class="col-sm-6">
		<div class="panel panel-default">
			<div class="panel-heading">
				<h2 class="panel-title">Fonctionnalités héritées</h2>
			</div>
			<div class="panel-body">
				<p>L'application <i class="fa fa-sitemap"></i>&nbsp;IP-Trevise se base sur le noyau de l'application blanche. L'application hérite donc des fonctionnalités suivantes :</p>
			</div>
			<div class="panel-footer">
				<ul class="list-unstyled">
					<li><i class="fa fa-user  fa-fw"></i>&nbsp;Gestion des utilisateurs</li>
					<li><i class="fa fa-users fa-fw"></i>&nbsp;Gestion des rôles</li>
					<li><i class="fa fa-lock  fa-fw"></i>&nbsp;Connexion sécurisée via Cerbère</li>
				</ul>
			</div>
		</div>
	</div>
</div>


