<?php $identified = !empty($this->zfcUserIdentity());?>
<div class="jumbotron">
    <h1><?php echo sprintf($this->translate('%sL\'Application blanche%s %sest un noyau%s'), '<i class="fa fa-file-o"></i>&nbsp;<span class="text-success">', '</span>','<small>','</small>') ?></h1>
    <p><?php
    	echo sprintf($this->translate('Cette %sapplication blanche ne répond à aucune fonctionnalité métier. Mais elle répond aux fonctionnalités standards d\'une application:'),
    		'<i class="fa fa-file-o"></i>&nbsp;') ?></p>
   	<div class="row">
   		<div class="col-md-4 col-xs-12 col-sm-6">
   			<ul class="list-unstyled">
		    	<li>
		    		<i class="fa fa-fw fa-user"></i>&nbsp;<?php echo $this->translate('Gestion des utilisateurs');?>
		    	</li>
		    	<li>
		    		<i class="fa fa-fw fa-users"></i>&nbsp;<?php echo $this->translate('Gestion des rôles');?>
		    	</li>
		    	<li>
		    		<i class="fa fa-fw fa-lock"></i>&nbsp;<?php echo $this->translate('Connexion via ZfcUser');?>
		    	</li>
		    </ul>
   		</div>
   		<div class="col-md-4 col-xs-12 col-sm-6">
   			<ul class="list-unstyled">
		    	<li>
		    		<i class="fa fa-fw fa-sort-amount-asc"></i>&nbsp;<?php echo $this->translate('Menu de navigation sécurisé');?>
		    	</li>
		    	<li>
		    		<i class="fa fa-fw fa-sitemap"></i>&nbsp;<?php echo $this->translate('Paramétrage du sitemap');?>
		    	</li>
		    	<li>
		    		<i class="fa fa-fw fa-minus-circle"></i>&nbsp;<?php echo $this->translate('Sécurisation des pages selon le profil');?>
		    	</li>
		    </ul>
   		</div>
   		<div class="col-md-4 col-xs-12 col-sm-6">
   			<ul class="list-unstyled">
		    	<li>
		    		<i class="fa fa-fw fa-clipboard"></i>&nbsp;<?php echo $this->translate('Gestion des icones');?>
		    	</li>
		    	<li>
		    		<i class="fa fa-fw fa-flag"></i>&nbsp;<?php echo $this->translate('Traduction multilingue');?>
		    	</li>
		    	<li>
		    		<i class="fa fa-fw fa-github-alt"></i>&nbsp;<?php echo $this->translate('Suivi des bugs et évolution avec Mantis');?>
		    	</li>
		    </ul>
   		</div>
   		</div>
    <p>
    	<span class="btn-group">
    		<a class="btn btn-default btn-lg" href="<?php echo $this->url('application',array('action' => 'exemple1'));?>">
    			<i class="fa fa-check-square-o"></i>&nbsp;<?php echo $this->translate('Page accessible') ?></a>
    		<a class="btn btn-default btn-lg" href="<?php echo $this->url('application',array('action' => 'lock'));?>">
    			<i class="fa fa-minus-circle"></i>&nbsp;<?php echo $this->translate('Page sécurisée') ?></a>
    		<?php if ($identified): ?>
    		<a class="btn btn-success btn-lg" href="<?php echo $this->url('zfcuser',array('action' => 'logout'));?>">
    			<i class="fa fa-sign-out"></i>&nbsp;<?php echo $this->translate('Sign Out') ?>
    		</a>
    		<?php else:?>
    		<a class="btn btn-success btn-lg" href="<?php echo $this->url('zfcuser',array('action' => 'login'));?>">
    			<i class="fa fa-sign-in"></i>&nbsp;<?php echo $this->translate('Sign In') ?>
    		</a>
    		<?php endif;?>
    	</span>
    </p>
</div>
