<?php $identified = !empty($this->identity());?>
<div class="jumbotron">
    <h1><?php echo sprintf($this->translate('%sIP-Trevise%s %sLa gestion de vos adresses IP%s'), '<i class="fa fa-sitemap"></i>&nbsp;<span class="text-success">', '</span>','<small>','</small>') ?></h1>
    <p><?php
    	echo sprintf($this->translate('Cette application a pour objectif de répondre aux besoins des administrateurs réseaux pour le suivi des adresses IP attribuées :'),
    		'<i class="fa fa-file-o"></i>&nbsp;') ?></p>
   	<div class="row">
   		<div class="col-md-6 col-xs-12 col-sm-6">
   			<ul class="list-unstyled">
		    	<li>
		    		<i class="fa fa-fw fa-sitemap"></i>&nbsp;<?php echo $this->translate('Gestion des sous-réseaux');?>
		    	</li>
		    	<li>
		    		<i class="fa fa-fw fa-share-alt"></i>&nbsp;<?php echo $this->translate('Gestion des adresses IP libres, réservées ou attribuées');?>
		    	</li>
		    	<li>
		    		<i class="fa fa-fw fa-desktop"></i>&nbsp;<?php echo $this->translate('Gestion des machines');?>
		    	</li>
		    </ul>
   		</div>
   		<div class="col-md-6 col-xs-12 col-sm-6">
   			<ul class="list-unstyled">
		    	<li>
		    		<i class="fa fa-fw fa-users"></i>&nbsp;<?php echo $this->translate('Gestion des utilisateurs, de leurs rôles');?>
		    	</li>
		    	<li>
		    		<i class="fa fa-fw fa-lock"></i>&nbsp;<?php echo $this->translate('Connexion sécurisées par Cerbère (phpCas)');?>
		    	</li>
		    	<li>
		    		<i class="fa fa-fw fa-github-alt"></i>&nbsp;<?php echo $this->translate('Suivi des bugs et évolution avec Mantis');?>
		    	</li>
		    </ul>
   		</div>
   		</div>
    <p>
    	<span class="btn-group">
    		<a class="btn btn-default btn-lg" href="<?php echo $this->url('application',array('action' => 'exemple1'));?>">
    			<i class="fa fa-check-square-o"></i>&nbsp;<?php echo $this->translate('Page accessible') ?></a>
    		<a class="btn btn-default btn-lg" href="<?php echo $this->url('application',array('action' => 'lock'));?>">
    			<i class="fa fa-minus-circle"></i>&nbsp;<?php echo $this->translate('Page sécurisée') ?></a>
    		<?php if ($identified): ?>
    		<a class="btn btn-success btn-lg" href="<?php echo $this->url('user-index',array('action'=>'logout'));?>">
    			<i class="fa fa-sign-out"></i>&nbsp;<?php echo $this->translate('Déconnexion') ?>
    		</a>
    		<?php else:?>
    		<a class="btn btn-success btn-lg" href="<?php echo $this->url('user-index',array('action'=>'login'));?>">
    			<i class="fa fa-sign-in"></i>&nbsp;<?php echo $this->translate('Connexion') ?>
    		</a>
    		<?php endif;?>
    	</span>
    </p>
</div>

<div class="row">

    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h2 class="panel-title"><i class="fa fa-code"></i>&nbsp;<?php echo $this->translate('Portail de développement') ?></h2>
            </div>
            <div class="panel-body">
                <p class="text-justify"><?php echo sprintf($this->translate('%sTitane%s est un service valorisant les développements. Vous travaillez dans l\'univers des routes&nbsp;? Vous ne trouvez pas de solution informatique infogérée capable de répondre à vos besoins spécifiques&nbsp;? Nos développements étant en constante évolution, n\'hésitez pas à nous faire part de vos demandes spécifiques que nous intégrerons rapidement à nos demandes d\'évolutions.'),
					'<i class="fa fa-road"></i><strong>&nbsp;', '</strong>', '<i class="fa fa-road"></i><strong>&nbsp;', '</strong>') ?></p>
                <p><a class="btn btn-default pull-right" href="<?php echo $this->url('application',array('action' => 'suivre'));?>"><?php echo $this->translate('Portail de développement') ?> &raquo;</a></p>
            </div>
        </div>
    </div>

    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><i class="fa fa-eye"></i>&nbsp;<?php echo $this->translate('Découvrir les fonctionnalités') ?></h3>
            </div>
            <div class="panel-body">
                <p class="text-justify"><?php echo $this->translate("L'équipe Titane du Cerema, forte de son expérience dans les équipements autoroutiers peut vous proposer des applications évolutives spécialisées dans l'exploitation routière. Cette application blanche ne dispose d'aucune fonctionnalité métier. Elle se veut un noyau central maintenu par l'équipe Trevise permettant de gérer les fonctionnalités courantes d'une application."); ?></p>
                <p><a class="btn btn-default pull-right" href="<?php echo $this->basePath('/main/fonction');?>"><?php echo sprintf($this->translate('Découvrir %sl\'Application blanche%s'),'<i class="fa fa-file-o"></i>&nbsp;<strong>','</strong>'); ?> <i class="fa fa-angle-double-right"></i></a></p>
            </div>
        </div>
    </div>

    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><i class="fa fa-question-circle"></i>&nbsp;<?php echo $this->translate('Aide &amp; Support') ?></h3>
            </div>
            <div class="panel-body">
                <p class="text-justify"><?php echo sprintf($this->translate("L'équipe Titane du Cerema de la DTerSO fournit une gamme de service permettant d'alléger vos ressources humaines")) ?></p>
                <ul>
                	<li><?php echo sprintf($this->translate("Une assistance téléphonique,")); ?></li>
                	<li><?php echo sprintf($this->translate("Assistance pour le dépploiement de l'application sur serveurs locaux ou centraux,")); ?></li>
                	<li><?php echo sprintf($this->translate("Développement et suivi du développement de vos applications personnalisées,")); ?></li>
                </ul>
                <p><a class="btn btn-default pull-right" href="<?php echo $this->basePath('/main/contact');?>"><i class="fa fa-phone"></i>&nbsp;<?php echo $this->translate('Contactez-nous') ?></a></p>
            </div>
        </div>
    </div>
</div>
