<?php $identified = !empty($this->identity());?>
<div class="jumbotron">
    <h1><?php echo sprintf($this->translate('%sL\'Application blanche%s %sest un noyau%s'), '<i class="fa fa-file-o"></i>&nbsp;<span class="text-success">', '</span>','<small>','</small>') ?></h1>
    <p><?php
    	echo sprintf($this->translate('Cette %sapplication blanche ne répond à aucune fonctionnalité métier. Mais elle répond aux fonctionnalités standards d\'une application:'),
    		'<i class="fa fa-file-o"></i>&nbsp;') ?></p>
   	<div class="row">
   		<div class="col-md-4 col-xs-12 col-sm-6">
   			<ul class="list-unstyled">
		    	<li>
		    		<i class="fa fa-fw fa-user"></i>&nbsp;<?php echo $this->translate('Gestion des utilisateurs');?>
		    	</li>
		    	<li>
		    		<i class="fa fa-fw fa-users"></i>&nbsp;<?php echo $this->translate('Gestion des rôles');?>
		    	</li>
		    	<li>
		    		<i class="fa fa-fw fa-lock"></i>&nbsp;<?php echo $this->translate('Connexion cerbérisée (phpCAS)');?>
		    	</li>
		    </ul>
   		</div>
   		<div class="col-md-4 col-xs-12 col-sm-6">
   			<ul class="list-unstyled">
		    	<li>
		    		<i class="fa fa-fw fa-sort-amount-asc"></i>&nbsp;<?php echo $this->translate('Menu de navigation sécurisé');?>
		    	</li>
		    	<li>
		    		<i class="fa fa-fw fa-sitemap"></i>&nbsp;<?php echo $this->translate('Paramétrage du sitemap');?>
		    	</li>
		    	<li>
		    		<i class="fa fa-fw fa-minus-circle"></i>&nbsp;<?php echo $this->translate('Sécurisation des pages selon le profil');?>
		    	</li>
		    </ul>
   		</div>
   		<div class="col-md-4 col-xs-12 col-sm-6">
   			<ul class="list-unstyled">
		    	<li>
		    		<i class="fa fa-fw fa-clipboard"></i>&nbsp;<?php echo $this->translate('Gestion des icones');?>
		    	</li>
		    	<li>
		    		<i class="fa fa-fw fa-flag"></i>&nbsp;<?php echo $this->translate('Traduction multilingue');?>
		    	</li>
		    	<li>
		    		<i class="fa fa-fw fa-github-alt"></i>&nbsp;<?php echo $this->translate('Suivi des bugs et évolution avec Mantis');?>
		    	</li>
		    </ul>
   		</div>
   		</div>
    <p>
    	<span class="btn-group">
    		<a class="btn btn-default btn-lg" href="<?php echo $this->url('application',array('action' => 'exemple1'));?>">
    			<i class="fa fa-check-square-o"></i>&nbsp;<?php echo $this->translate('Page accessible') ?></a>
    		<a class="btn btn-default btn-lg" href="<?php echo $this->url('application',array('action' => 'lock'));?>">
    			<i class="fa fa-minus-circle"></i>&nbsp;<?php echo $this->translate('Page sécurisée') ?></a>
    		<?php if ($identified): ?>
    		<a class="btn btn-success btn-lg" href="<?php echo $this->url('user-index',array('action'=>'logout'));?>">
    			<i class="fa fa-sign-out"></i>&nbsp;<?php echo $this->translate('Déconnexion') ?>
    		</a>
    		<?php else:?>
    		<a class="btn btn-success btn-lg" href="<?php echo $this->url('user-index',array('action'=>'login'));?>">
    			<i class="fa fa-sign-in"></i>&nbsp;<?php echo $this->translate('Connexion') ?>
    		</a>
    		<?php endif;?>
    	</span>
    </p>
</div>

<div class="row">

    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h2 class="panel-title"><i class="fa fa-code"></i>&nbsp;<?php echo $this->translate('Portail de développement') ?></h2>
            </div>
            <div class="panel-body">
                <p class="text-justify"><?php echo sprintf($this->translate('%sTitane%s est un service valorisant les développements liés aux services de transports intelligents. Vous travaillez dans l\'univers des routes&nbsp;? Vous ne trouvez pas de solution informatique infogérée capable de répondre à vos besoins spécifiques&nbsp;? Nos développements étant en constante évolution, n\'hésitez pas à nous faire part de vos demandes spécifiques que nous intégrerons rapidement à nos applications.'),
					'<i class="fa fa-road"></i><strong>&nbsp;', '</strong>', '<i class="fa fa-road"></i><strong>&nbsp;', '</strong>') ?></p>
                <p><a class="btn btn-default pull-right" href="<?php echo $this->url('application',array('action' => 'suivre'));?>"><?php echo $this->translate('Portail de développement') ?> &raquo;</a></p>
            </div>
        </div>
    </div>

    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><i class="fa fa-eye"></i>&nbsp;<?php echo $this->translate('Découvrir les fonctionnalités') ?></h3>
            </div>
            <div class="panel-body">
                <p class="text-justify"><?php echo $this->translate("L'application IP-Trevise permet de suivre les attributions d'adresses IP dans des réseaux dépourvus de DHCP."); ?></p>
                <p><a class="btn btn-default pull-right" href="<?php echo $this->url('application',array('action' => 'fonction'));?>"><?php echo sprintf($this->translate('Découvrir %sIP Trevise%s'),'<i class="fa fa-sitemap"></i>&nbsp;<strong>','</strong>'); ?> <i class="fa fa-angle-double-right"></i></a></p>
            </div>
        </div>
    </div>

    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><i class="fa fa-question-circle"></i>&nbsp;<?php echo $this->translate('Aide &amp; Support') ?></h3>
            </div>
            <div class="panel-body">
                <p class="text-justify"><?php echo sprintf($this->translate("L'équipe Titane du Cerema de la DTerSO fournit une gamme de service permettant d'alléger vos ressources humaines")) ?></p>
                <ul>
                	<li><?php echo sprintf($this->translate("Une assistance téléphonique,")); ?></li>
                	<li><?php echo sprintf($this->translate("Assistance pour le déploiement de l'application sur serveurs locaux ou centraux,")); ?></li>
                	<li><?php echo sprintf($this->translate("Développement et suivi du développement de vos applications personnalisées,")); ?></li>
                </ul>
                <p><a class="btn btn-default pull-right" href="<?php echo $this->basePath('/main/contact');?>"><i class="fa fa-phone"></i>&nbsp;<?php echo $this->translate('Contactez-nous') ?></a></p>
            </div>
        </div>
    </div>
</div>
